# Generated by Django 3.0.6 on 2020-11-23 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Enter a valid value', regex='^[a-zA-Z0-9 ]+$')])),
                ('ubicacion', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid value', regex='^[a-zA-Z0-9 ]+$')])),
                ('web', models.CharField(max_length=50, null=True)),
                ('telefono', models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value', regex='^[0-9]+$'), django.core.validators.MaxValueValidator(999999999)])),
                ('apertura', models.TimeField(null=True)),
                ('cierre', models.TimeField(null=True)),
            ],
        ),
    ]
