# Generated by Django 3.0.6 on 2020-07-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200703_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuincluye',
            old_name='postreIncluido',
            new_name='postre',
        ),
    ]
