# Generated by Django 3.0.6 on 2020-07-28 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_platoscategorias_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menubar',
            old_name='postre',
            new_name='celiaco',
        ),
        migrations.RenameField(
            model_name='menubar',
            old_name='segundo',
            new_name='vegano',
        ),
        migrations.RemoveField(
            model_name='menubar',
            name='primero',
        ),
        migrations.AddField(
            model_name='menubar',
            name='posicion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.RegexValidator(message='Enter a valid value', regex='^[1-3]+$'), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menubar',
            name='vegetariano',
            field=models.BooleanField(default=False),
        ),
    ]
