# Generated by Django 3.0.6 on 2020-08-02 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200728_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuincluye',
            name='anotacion',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuincluye',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
