# Generated by Django 3.0.6 on 2020-08-02 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200802_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuincluye',
            name='anotacion',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='menuincluye',
            name='menuPrecio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
