# Generated by Django 3.0.6 on 2020-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200802_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuincluye',
            name='bebida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuincluye',
            name='pan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuincluye',
            name='postre',
            field=models.BooleanField(default=False),
        ),
    ]
